// Subset of the ALL_COUNTRIES list in globe.js, kept in sync manually.
// We only need name resolution here; lat/lng/iso live in globe.js for the map.
const COUNTRIES = [
  // Format: [canonicalEn, ru]
  ['Afghanistan', 'Афганистан'],
  ['Albania', 'Албания'],
  ['Algeria', 'Алжир'],
  ['Andorra', 'Андорра'],
  ['Angola', 'Ангола'],
  ['Antigua and Barbuda', 'Антигуа и Барбуда'],
  ['Argentina', 'Аргентина'],
  ['Armenia', 'Армения'],
  ['Australia', 'Австралия'],
  ['Austria', 'Австрия'],
  ['Azerbaijan', 'Азербайджан'],
  ['Bahamas', 'Багамы'],
  ['Bahrain', 'Бахрейн'],
  ['Bangladesh', 'Бангладеш'],
  ['Barbados', 'Барбадос'],
  ['Belarus', 'Беларусь'],
  ['Belgium', 'Бельгия'],
  ['Belize', 'Белиз'],
  ['Benin', 'Бенин'],
  ['Bhutan', 'Бутан'],
  ['Bolivia', 'Боливия'],
  ['Bosnia and Herzegovina', 'Босния и Герцеговина'],
  ['Botswana', 'Ботсвана'],
  ['Brazil', 'Бразилия'],
  ['Brunei', 'Бруней'],
  ['Bulgaria', 'Болгария'],
  ['Burkina Faso', 'Буркина-Фасо'],
  ['Burundi', 'Бурунди'],
  ['Cambodia', 'Камбоджа'],
  ['Cameroon', 'Камерун'],
  ['Canada', 'Канада'],
  ['Cape Verde', 'Кабо-Верде'],
  ['Central African Republic', 'ЦАР'],
  ['Chad', 'Чад'],
  ['Chile', 'Чили'],
  ['China', 'Китай'],
  ['Colombia', 'Колумбия'],
  ['Comoros', 'Коморы'],
  ['Congo', 'Республика Конго'],
  ['Costa Rica', 'Коста-Рика'],
  ['Croatia', 'Хорватия'],
  ['Cuba', 'Куба'],
  ['Cyprus', 'Кипр'],
  ['Czech Republic', 'Чехия'],
  ['Democratic Republic of Congo', 'ДР Конго'],
  ['Denmark', 'Дания'],
  ['Djibouti', 'Джибути'],
  ['Dominica', 'Доминика'],
  ['Dominican Republic', 'Доминиканская Республика'],
  ['East Timor', 'Восточный Тимор'],
  ['Ecuador', 'Эквадор'],
  ['Egypt', 'Египет'],
  ['El Salvador', 'Сальвадор'],
  ['Equatorial Guinea', 'Экваториальная Гвинея'],
  ['Eritrea', 'Эритрея'],
  ['Estonia', 'Эстония'],
  ['Eswatini', 'Эсватини'],
  ['Ethiopia', 'Эфиопия'],
  ['Fiji', 'Фиджи'],
  ['Finland', 'Финляндия'],
  ['France', 'Франция'],
  ['Gabon', 'Габон'],
  ['Gambia', 'Гамбия'],
  ['Georgia', 'Грузия'],
  ['Germany', 'Германия'],
  ['Ghana', 'Гана'],
  ['Greece', 'Греция'],
  ['Grenada', 'Гренада'],
  ['Guatemala', 'Гватемала'],
  ['Guinea', 'Гвинея'],
  ['Guinea-Bissau', 'Гвинея-Бисау'],
  ['Guyana', 'Гайана'],
  ['Haiti', 'Гаити'],
  ['Honduras', 'Гондурас'],
  ['Hong Kong', 'Гонконг'],
  ['Hungary', 'Венгрия'],
  ['Iceland', 'Исландия'],
  ['India', 'Индия'],
  ['Indonesia', 'Индонезия'],
  ['Iran', 'Иран'],
  ['Iraq', 'Ирак'],
  ['Ireland', 'Ирландия'],
  ['Israel', 'Израиль'],
  ['Italy', 'Италия'],
  ['Ivory Coast', "Кот-д'Ивуар"],
  ['Jamaica', 'Ямайка'],
  ['Japan', 'Япония'],
  ['Jordan', 'Иордания'],
  ['Kazakhstan', 'Казахстан'],
  ['Kenya', 'Кения'],
  ['Kiribati', 'Кирибати'],
  ['Kosovo', 'Косово'],
  ['Kuwait', 'Кувейт'],
  ['Kyrgyzstan', 'Киргизия'],
  ['Laos', 'Лаос'],
  ['Latvia', 'Латвия'],
  ['Lebanon', 'Ливан'],
  ['Lesotho', 'Лесото'],
  ['Liberia', 'Либерия'],
  ['Libya', 'Ливия'],
  ['Liechtenstein', 'Лихтенштейн'],
  ['Lithuania', 'Литва'],
  ['Luxembourg', 'Люксембург'],
  ['Madagascar', 'Мадагаскар'],
  ['Malawi', 'Малави'],
  ['Malaysia', 'Малайзия'],
  ['Maldives', 'Мальдивы'],
  ['Mali', 'Мали'],
  ['Malta', 'Мальта'],
  ['Marshall Islands', 'Маршалловы Острова'],
  ['Mauritania', 'Мавритания'],
  ['Mauritius', 'Маврикий'],
  ['Mexico', 'Мексика'],
  ['Micronesia', 'Микронезия'],
  ['Moldova', 'Молдова'],
  ['Monaco', 'Монако'],
  ['Mongolia', 'Монголия'],
  ['Montenegro', 'Черногория'],
  ['Morocco', 'Марокко'],
  ['Mozambique', 'Мозамбик'],
  ['Myanmar', 'Мьянма'],
  ['Namibia', 'Намибия'],
  ['Nauru', 'Науру'],
  ['Nepal', 'Непал'],
  ['Netherlands', 'Нидерланды'],
  ['New Zealand', 'Новая Зеландия'],
  ['Nicaragua', 'Никарагуа'],
  ['Niger', 'Нигер'],
  ['Nigeria', 'Нигерия'],
  ['North Korea', 'Северная Корея'],
  ['North Macedonia', 'Северная Македония'],
  ['Norway', 'Норвегия'],
  ['Oman', 'Оман'],
  ['Pakistan', 'Пакистан'],
  ['Palau', 'Палау'],
  ['Palestine', 'Палестина'],
  ['Panama', 'Панама'],
  ['Papua New Guinea', 'Папуа — Новая Гвинея'],
  ['Paraguay', 'Парагвай'],
  ['Peru', 'Перу'],
  ['Philippines', 'Филиппины'],
  ['Poland', 'Польша'],
  ['Portugal', 'Португалия'],
  ['Qatar', 'Катар'],
  ['Romania', 'Румыния'],
  ['Russia', 'Россия'],
  ['Rwanda', 'Руанда'],
  ['Saint Kitts and Nevis', 'Сент-Китс и Невис'],
  ['Saint Lucia', 'Сент-Люсия'],
  ['Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины'],
  ['Samoa', 'Самоа'],
  ['San Marino', 'Сан-Марино'],
  ['Sao Tome and Principe', 'Сан-Томе и Принсипи'],
  ['Saudi Arabia', 'Саудовская Аравия'],
  ['Senegal', 'Сенегал'],
  ['Serbia', 'Сербия'],
  ['Seychelles', 'Сейшелы'],
  ['Sierra Leone', 'Сьерра-Леоне'],
  ['Singapore', 'Сингапур'],
  ['Slovakia', 'Словакия'],
  ['Slovenia', 'Словения'],
  ['Solomon Islands', 'Соломоновы Острова'],
  ['Somalia', 'Сомали'],
  ['South Africa', 'ЮАР'],
  ['South Korea', 'Южная Корея'],
  ['South Sudan', 'Южный Судан'],
  ['Spain', 'Испания'],
  ['Sri Lanka', 'Шри-Ланка'],
  ['Sudan', 'Судан'],
  ['Suriname', 'Суринам'],
  ['Sweden', 'Швеция'],
  ['Switzerland', 'Швейцария'],
  ['Syria', 'Сирия'],
  ['Taiwan', 'Тайвань'],
  ['Tajikistan', 'Таджикистан'],
  ['Tanzania', 'Танзания'],
  ['Thailand', 'Таиланд'],
  ['Togo', 'Того'],
  ['Tonga', 'Тонга'],
  ['Trinidad and Tobago', 'Тринидад и Тобаго'],
  ['Tunisia', 'Тунис'],
  ['Turkey', 'Турция'],
  ['Turkmenistan', 'Туркменистан'],
  ['Tuvalu', 'Тувалу'],
  ['Uganda', 'Уганда'],
  ['Ukraine', 'Украина'],
  ['United Arab Emirates', 'ОАЭ'],
  ['United Kingdom', 'Великобритания'],
  ['United States', 'США'],
  ['Uruguay', 'Уругвай'],
  ['Uzbekistan', 'Узбекистан'],
  ['Vanuatu', 'Вануату'],
  ['Vatican City', 'Ватикан'],
  ['Venezuela', 'Венесуэла'],
  ['Vietnam', 'Вьетнам'],
  ['Yemen', 'Йемен'],
  ['Zambia', 'Замбия'],
  ['Zimbabwe', 'Зимбабве'],
];

// Build lookup maps once at module load.
const BY_EN = new Map();
const BY_RU = new Map();
for (const [en, ru] of COUNTRIES) {
  BY_EN.set(en.toLowerCase(), en);
  BY_RU.set(ru.toLowerCase(), en);
}

export function canonicalCountry(input) {
  if (input == null) return null;
  const k = String(input).trim().toLowerCase();
  if (!k) return null;
  return BY_EN.get(k) || BY_RU.get(k) || null;
}

export function isKnownCountry(input) {
  return canonicalCountry(input) !== null;
}
